### ISSUE TITLE
 Community Discussion Forum > Bounty Question > Search functionality is not working correctly and is not returning precise results. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#201]
![14](https://user-images.githubusercontent.com/60692597/208524361-26e6b423-4d26-4ab3-b4fd-e8db827ffaa2.png)

**Comment by bioworkflows** [comment]
This is caused by frequent update and restart of the staging server, which caused missing indexes. If some topics are missing, editing the topic and re-saving them will add them to the index. 

I have now re-generated all indexes and the search box should work now.

**Comment by Mashhood-Ehsan** [comment]
The issue is still not fixed, so re-opening it.

![screencapture-staging-bioworkflows-forum-forum-general-2022-12-23-02_22_52](https://user-images.githubusercontent.com/60692597/209319027-2ea9b4f2-59a2-4088-a951-c7f809db560f.png)

**Comment by BoPeng** [comment]
ok, the indexes are there and the search is semi-successful. If I search just by 'subject', then `Test Subject' will appear, if I search by `test subject`, a bunch of topics that contain `test` would appear, but the one `Test Subject` is not in the front. Likely because the search results are ordered by date, not by relevance.

**Comment by bioworkflows** [comment]
This has been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it. 

![9](https://user-images.githubusercontent.com/60692597/219971766-4ea47f3a-c60b-4351-a6f1-35a0f4ee1094.PNG)
